jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.private_key }}
          app_id: ${{ secrets.app_id }}
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: ["^echo .*"]
          RENOVATE_LOG_LEVEL: "debug"
          RENOVATE_USERNAME: "renovate-repro-20672[bot]"
          RENOVATE_GIT_AUTHOR: "Self-hosted Renovate Bot <79356887+renovate-repro-20672[bot]@users.noreply.github.enterprise.com>"
          RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }}
          RENOVATE_REPOSITORIES: ["MDietz135/renovate-repro-20672"]
       